# 1. Create a NumPy array of integers from 1 to 10.

In [3]:
import numpy as np

In [4]:
array1=np.arange(1,11)

In [5]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2.Create a 2x3 NumPy array filled with zeros.

In [6]:
array2=np.zeros((2,3))

In [7]:
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

# 3. Create a NumPy array of even numbers from 2 to 20

In [8]:
array3=np.arange(2,21,2)

In [9]:
array3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# 4. Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division between the two arrays

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1

array([1, 2, 3])

In [11]:
arr2

array([4, 5, 6])

In [12]:
arr1+arr2

array([5, 7, 9])

In [13]:
arr1-arr2

array([-3, -3, -3])

In [14]:
arr1*arr2

array([ 4, 10, 18])

In [15]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

# Compute the mean, median, and standard deviation of a NumPy array containing 100 random numbers

In [16]:
array3=np.random.randint(1,1000,100)

In [17]:
array3

array([501, 385, 446, 552, 728, 575,  97, 123, 579, 698, 562, 528, 844,
       431, 895, 109,  65,  68, 544, 329, 376, 349, 407,  33, 306, 373,
       194, 617, 986, 391,  41, 541, 985, 692, 251, 374, 998, 814, 587,
       477, 419, 467, 722, 410, 512, 800, 515, 587,  99, 589, 167, 123,
       493, 595, 577, 497, 883, 299, 711, 194, 542, 756, 139, 547, 440,
       962, 661, 426, 577, 875, 542,  24, 148, 310, 908, 522,  66, 151,
       549, 638, 559, 605, 219, 265, 438, 472, 165, 208, 479,   3, 738,
       348, 514, 150, 332, 878, 389, 550, 170, 169])

In [18]:
array3.sort()
array3

array([  3,  24,  33,  41,  65,  66,  68,  97,  99, 109, 123, 123, 139,
       148, 150, 151, 165, 167, 169, 170, 194, 194, 208, 219, 251, 265,
       299, 306, 310, 329, 332, 348, 349, 373, 374, 376, 385, 389, 391,
       407, 410, 419, 426, 431, 438, 440, 446, 467, 472, 477, 479, 493,
       497, 501, 512, 514, 515, 522, 528, 541, 542, 542, 544, 547, 549,
       550, 552, 559, 562, 575, 577, 577, 579, 587, 587, 589, 595, 605,
       617, 638, 661, 692, 698, 711, 722, 728, 738, 756, 800, 814, 844,
       875, 878, 883, 895, 908, 962, 985, 986, 998])

In [19]:
print("mean",array3.mean())
print("median",np.median(array3))
print("standard deviation",np.std(array3))

mean 459.44
median 478.0
standard deviation 251.1667700950904


# 6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a shape of (3, 4)

In [20]:
array4=np.random.randint(1,20,12).reshape(3,4)

In [21]:
array4

array([[ 7, 15, 12, 19],
       [ 1,  7, 10, 17],
       [ 2,  5, 12, 10]])

# 7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in the array using NumPy functions.


In [22]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [23]:
arr**2

array([ 1,  4,  9, 16, 25])

# 8. Create a 5x5 identity matrix using NumPy.


In [24]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])

In [25]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [26]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [27]:
a.dot(b)

32

# 10.Find the index of the maximum value and the index of the minimum value in a NumPy array

In [28]:
array5=np.array([5,25,67,89,76,45,34,54,87,67,23,12,14,35,46,57,7,989,79,90,87,65,43,32,21])

In [29]:
array5

array([  5,  25,  67,  89,  76,  45,  34,  54,  87,  67,  23,  12,  14,
        35,  46,  57,   7, 989,  79,  90,  87,  65,  43,  32,  21])

In [30]:
array5.argmax()

17

In [31]:
array5.argmin()

0

# 11.Concatenate two random NumPy arrays horizontally and vertically.

In [32]:
ar1=np.random.randint(0,100,25).reshape(5,5)

In [33]:
ar1

array([[ 6, 41, 53, 95, 27],
       [ 5, 52, 22, 90, 16],
       [71, 82, 48, 20, 82],
       [68, 64, 36, 84, 51],
       [ 5,  1, 78, 74, 81]])

In [34]:
ar2=np.random.randint(50,150,25).reshape(5,5)

In [35]:
ar2

array([[ 68, 106,  51, 104, 126],
       [113, 140, 131,  57,  79],
       [ 70,  76, 105, 119,  82],
       [ 66,  96, 116,  99, 143],
       [ 81,  70, 100, 135, 147]])

In [36]:
np.concatenate((ar1,ar2),axis=1)

array([[  6,  41,  53,  95,  27,  68, 106,  51, 104, 126],
       [  5,  52,  22,  90,  16, 113, 140, 131,  57,  79],
       [ 71,  82,  48,  20,  82,  70,  76, 105, 119,  82],
       [ 68,  64,  36,  84,  51,  66,  96, 116,  99, 143],
       [  5,   1,  78,  74,  81,  81,  70, 100, 135, 147]])

In [37]:
np.concatenate((ar1,ar2))

array([[  6,  41,  53,  95,  27],
       [  5,  52,  22,  90,  16],
       [ 71,  82,  48,  20,  82],
       [ 68,  64,  36,  84,  51],
       [  5,   1,  78,  74,  81],
       [ 68, 106,  51, 104, 126],
       [113, 140, 131,  57,  79],
       [ 70,  76, 105, 119,  82],
       [ 66,  96, 116,  99, 143],
       [ 81,  70, 100, 135, 147]])

# 12.Given a 2D NumPy array, calculate the sum of each row and each column separately.

In [38]:
ar3=np.random.randint(1,35,20).reshape(4,5)
ar3

array([[15, 14, 20, 25, 19],
       [31, 18,  7,  2, 34],
       [ 3, 20, 16, 14,  8],
       [34, 17, 30, 21, 13]])

In [39]:
ar3.sum(1) #sum of each row

array([ 93,  92,  61, 115])

In [40]:
ar3.sum(0) # sum of each column

array([83, 69, 73, 62, 74])

#13.Find the common elements between two NumPy arrays

In [41]:
ar4=np.array([23,45,67,89,90,13,46,79,24,68,10,25,76,86])
ar4

array([23, 45, 67, 89, 90, 13, 46, 79, 24, 68, 10, 25, 76, 86])

In [42]:
ar5=([98,76,54,43,21,34,78,23,46,24,76,13,97,96,68,76,30])
ar5

[98, 76, 54, 43, 21, 34, 78, 23, 46, 24, 76, 13, 97, 96, 68, 76, 30]

In [43]:
np.intersect1d(ar4,ar5)

array([13, 23, 24, 46, 68, 76])

#14.Replace all negative values in a NumPy array with zeros

In [44]:
ary1=np.random.randint(-10,30,10).reshape(2,5)
ary1

array([[ 24,  26,  15,  -7,  -8],
       [-10,  21,   9,  28,   1]])

In [45]:
ary1[ary1<0]=0

In [46]:
ary1

array([[24, 26, 15,  0,  0],
       [ 0, 21,  9, 28,  1]])

#15.Create a NumPy array with random integers between 1 and 100 and then sort it in ascending order.

In [47]:
ary2=np.random.randint(1,100,50)
ary2

array([56, 40, 92, 13, 64, 41, 75, 66, 84, 79, 41, 16, 69,  5, 63,  4,  5,
       22, 81, 18, 97, 80,  6, 76, 35, 56, 85, 92, 85,  4, 76, 29,  9, 60,
       84, 70, 71, 58, 31, 33,  7, 33, 67, 64, 47, 34, 32, 96, 97, 34])

In [48]:
ary2.sort()
ary2

array([ 4,  4,  5,  5,  6,  7,  9, 13, 16, 18, 22, 29, 31, 32, 33, 33, 34,
       34, 35, 40, 41, 41, 47, 56, 56, 58, 60, 63, 64, 64, 66, 67, 69, 70,
       71, 75, 76, 76, 79, 80, 81, 84, 84, 85, 85, 92, 92, 96, 97, 97])

#16.Calculate the element-wise absolute difference between two NumPy arrays

In [49]:
ary3=np.array([35,65,7,45,3,4,67,98,34,56,7,9,45,2,122,45,70])

In [50]:
ary4=np.array([24,34,23,5,8,4,83,21,3,5,7,9,45,67,1,22,44])

In [51]:
np.abs(ary3-ary4)

array([ 11,  31,  16,  40,   5,   0,  16,  77,  31,  51,   0,   0,   0,
        65, 121,  23,  26])

#17.Given a 2D NumPy array, extract the first row and the last column

In [52]:
ary4=np.random.randint(1,100,24).reshape(6,4)
ary4

array([[45,  9, 88, 35],
       [97, 79, 70, 52],
       [20, 97, 28, 30],
       [81, 34, 74, 55],
       [97, 54, 71, 99],
       [10, 52, 10, 74]])

In [53]:
print("first row")
print(ary4[0])
print("last column")
print(ary4[:,[-1]])

first row
[45  9 88 35]
last column
[[35]
 [52]
 [30]
 [55]
 [99]
 [74]]


#18.Slice a 1D NumPy array to get every other element

In [54]:
ary5=np.random.randint(1,100,20)
ary5

array([83, 41, 11, 80, 80, 74,  9, 80, 90, 48, 45, 33,  2, 27,  8, 39, 14,
       80,  6, 57])

In [55]:
ary5[::2]

array([83, 11, 80,  9, 90, 45,  2,  8, 14,  6])

#19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2 elements


In [56]:
ary6=np.random.randint(1,50,24).reshape(6,4)
ary6

array([[43, 18, 42, 14],
       [13, 11, 28,  5],
       [31, 20,  3, 28],
       [21, 30, 16, 40],
       [ 7, 41, 25, 23],
       [41, 34, 40, 44]])

In [57]:
row,col=ary6.shape
r=row//2-1
c=col//2-1
print(ary6[r:r+2,[c,c+1]])

[[20  3]
 [30 16]]


#20.Reverse a 1D NumPy array using slicing

In [58]:
ar=np.array([12,34,56,78,90,98,76,54,32,10,135,61,52,43,91,65,20])
print("\t array ",ar)
arr=ar[::-1]
print("reversed array",arr)

	 array  [ 12  34  56  78  90  98  76  54  32  10 135  61  52  43  91  65  20]
reversed array [ 20  65  91  43  52  61 135  10  32  54  76  98  90  78  56  34  12]
